package model;
// Generated 17 Mar, 2024 8:36:35 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String name;
     private String dateOfBirth;
     private String gender;
     private String address;
     private String city;
     private String state;
     private String loginId;
     private String password;

    public Student() {
    }

	
    public Student(int id, String name, String dateOfBirth, String gender, String address, String city, String loginId, String password) {
        this.id = id;
        this.name = name;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.address = address;
        this.city = city;
        this.loginId = loginId;
        this.password = password;
    }
    public Student(int id, String name, String dateOfBirth, String gender, String address, String city, String state, String loginId, String password) {
       this.id = id;
       this.name = name;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.address = address;
       this.city = city;
       this.state = state;
       this.loginId = loginId;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


